//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AJAX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property
    {
        public string Street { get; set; }
        public string Number { get; set; }
        public string Suburb { get; set; }
        public string State { get; set; }
        public string Postcode { get; set; }
        public byte Type { get; set; }
        public decimal Price { get; set; }
        public System.DateTime SoldDate { get; set; }
    }
}
