//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchemaFirstEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public Company()
        {
            this.EndOfDays = new HashSet<EndOfDay>();
        }
    
        public string Code { get; set; }
        public string Name { get; set; }
        public string Group { get; set; }
    
        public virtual IndustryGroup IndustryGroup { get; set; }
        public virtual ICollection<EndOfDay> EndOfDays { get; set; }
        public virtual WatchList WatchList { get; set; }
    }
}
